// GENERATED by scripts/extract-youtube.mjs — do not edit manually
export type PortfolioCategory = 'Mars' | 'Hymne'

export type PortfolioType =
  | 'Sekolah'
  | 'Yayasan'
  | 'Pesantren'
  | 'Instansi'
  | 'Perusahaan'
  | 'Lembaga'

export interface PortfolioItem {
  id: string
  youtubeId: string
  title: string
  category: PortfolioCategory
  type: PortfolioType
  client: string
  year: string
  description: string
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: 'hidayah-klaten',
    youtubeId: 'v4c3EQwolrI',
    title: 'Mars Hidayah Klaten',
    category: 'Mars',
    type: 'Yayasan',
    client: 'Hidayah Klaten',
    year: '2026',
    description: 'Mars Hidayah Klaten — lagu Mars yayasan untuk Hidayah Klaten oleh ALF Production.'
  },
  {
    id: 'sit-kota-wali-demak',
    youtubeId: 'UAaj0IvUJyQ',
    title: 'Mars SIT Kota Wali Demak',
    category: 'Mars',
    type: 'Sekolah',
    client: 'SIT Kota Wali Demak',
    year: '2026',
    description: 'Mars SIT Kota Wali Demak — lagu Mars sekolah untuk SIT Kota Wali Demak oleh ALF Production.'
  },
  {
    id: 'sit-al-furqon-slawi-tegal',
    youtubeId: 'D7W38ZQG54s',
    title: 'Mars SIT Al Furqon Slawi Tegal',
    category: 'Mars',
    type: 'Sekolah',
    client: 'SIT Al Furqon Slawi Tegal',
    year: '2026',
    description: 'Mars SIT Al Furqon Slawi Tegal — lagu Mars sekolah untuk SIT Al Furqon Slawi Tegal oleh ALF Production.'
  },
  {
    id: 'sit-mutiara-hati-semarang',
    youtubeId: 'uknn15IcWd8',
    title: 'Mars SIT Mutiara Hati Semarang',
    category: 'Mars',
    type: 'Sekolah',
    client: 'SIT Mutiara Hati Semarang',
    year: '2026',
    description: 'Mars SIT Mutiara Hati Semarang — lagu Mars sekolah untuk SIT Mutiara Hati Semarang oleh ALF Production.'
  },
  {
    id: 'al-barokah-walhikmah-jambi',
    youtubeId: 'G_-h_yHH7og',
    title: 'Mars Al Barokah Walhikmah Jambi',
    category: 'Mars',
    type: 'Pesantren',
    client: 'Al Barokah Walhikmah Jambi',
    year: '2026',
    description: 'Mars Al Barokah Walhikmah Jambi — lagu Mars pesantren untuk Al Barokah Walhikmah Jambi oleh ALF Production.'
  },
  {
    id: 'abi-ummi-boyolali',
    youtubeId: '8im6P9KHZ7k',
    title: 'Mars Abi Ummi Boyolali',
    category: 'Mars',
    type: 'Yayasan',
    client: 'Abi Ummi Boyolali',
    year: '2026',
    description: 'Mars Abi Ummi Boyolali — lagu Mars yayasan untuk Abi Ummi Boyolali oleh ALF Production.'
  },
  {
    id: 'rs-permata-hati-riau',
    youtubeId: '1P4hkZLE050',
    title: 'Mars RS Permata Hati - Riau',
    category: 'Mars',
    type: 'Instansi',
    client: 'RS Permata Hati - Riau',
    year: '2026',
    description: 'Mars RS Permata Hati - Riau — lagu Mars instansi untuk RS Permata Hati - Riau oleh ALF Production.'
  },
  {
    id: 'smkn-5-berau-kalimantan-timur',
    youtubeId: 'vpUX6Wx1xNY',
    title: 'Mars SMKN 5 Berau - Kalimantan Timur',
    category: 'Mars',
    type: 'Sekolah',
    client: 'SMKN 5 Berau - Kalimantan Timur',
    year: '2026',
    description: 'Mars SMKN 5 Berau - Kalimantan Timur — lagu Mars sekolah untuk SMKN 5 Berau - Kalimantan Timur oleh ALF Production.'
  },
  {
    id: 'berlindo-mitra-utama',
    youtubeId: 'erf-wwdgRbo',
    title: 'Mars Berlindo Mitra Utama',
    category: 'Mars',
    type: 'Perusahaan',
    client: 'Berlindo Mitra Utama',
    year: '2026',
    description: 'Mars Berlindo Mitra Utama — lagu Mars perusahaan untuk Berlindo Mitra Utama oleh ALF Production.'
  },
  {
    id: 'nutrisius-sari-persada',
    youtubeId: 'Yd9BCt42GCE',
    title: 'Mars Nutrisius Sari Persada',
    category: 'Mars',
    type: 'Perusahaan',
    client: 'Nutrisius Sari Persada',
    year: '2026',
    description: 'Mars Nutrisius Sari Persada — lagu Mars perusahaan untuk Nutrisius Sari Persada oleh ALF Production.'
  },
  {
    id: 'csr-cleaning',
    youtubeId: '-yG8x1pEpqE',
    title: 'Mars CSR Cleaning',
    category: 'Mars',
    type: 'Perusahaan',
    client: 'CSR Cleaning',
    year: '2026',
    description: 'Mars CSR Cleaning — lagu Mars perusahaan untuk CSR Cleaning oleh ALF Production.'
  },
  {
    id: 'wira-andhang-pandhega',
    youtubeId: '8a6c9aGlXYY',
    title: 'Mars Wira Andhang Pandhega',
    category: 'Mars',
    type: 'Instansi',
    client: 'Wira Andhang Pandhega',
    year: '2026',
    description: 'Mars Wira Andhang Pandhega — lagu Mars instansi untuk Wira Andhang Pandhega oleh ALF Production.'
  },
  {
    id: 'smait-hidayah-klaten',
    youtubeId: 'dh1tCiPscPo',
    title: 'Mars SMAIT Hidayah Klaten',
    category: 'Mars',
    type: 'Sekolah',
    client: 'SMAIT Hidayah Klaten',
    year: '2026',
    description: 'Mars SMAIT Hidayah Klaten — lagu Mars sekolah untuk SMAIT Hidayah Klaten oleh ALF Production.'
  },
  {
    id: 'ppc-ciamis',
    youtubeId: 'lBwt0X-KDSo',
    title: 'Mars PPC Ciamis',
    category: 'Mars',
    type: 'Lembaga',
    client: 'PPC Ciamis',
    year: '2026',
    description: 'Mars PPC Ciamis — lagu Mars lembaga untuk PPC Ciamis oleh ALF Production.'
  },
  {
    id: 'baitul-quran-riau',
    youtubeId: 'utaFyUsOJ5E',
    title: 'Mars Baitul Quran Riau',
    category: 'Mars',
    type: 'Pesantren',
    client: 'Baitul Quran Riau',
    year: '2026',
    description: 'Mars Baitul Quran Riau — lagu Mars pesantren untuk Baitul Quran Riau oleh ALF Production.'
  },
]

export const portfolioTypeLabels: PortfolioType[] = [
  'Sekolah',
  'Yayasan',
  'Pesantren',
  'Instansi',
  'Perusahaan',
  'Lembaga'
]

export const portfolioFilters: string[] = ['Semua', ...portfolioTypeLabels]
