import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const DEFAULT_URL = 'https://www.youtube.com/@alfproduction-id/videos'

const args = process.argv.slice(2)

function argValue(name) {
  const idx = args.indexOf(name)
  return idx !== -1 ? args[idx + 1] : undefined
}

async function loadHtml(source) {
  if (!source) source = DEFAULT_URL
  if (source.startsWith('http')) {
    const res = await fetch(source, {
      headers: { 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36' }
    })
    if (!res.ok) throw new Error(`fetch ${source} -> HTTP ${res.status}`)
    return res.text()
  }
  return readFile(source, 'utf8')
}

function collectLockups(node, out = []) {
  if (Array.isArray(node)) {
    for (const item of node) collectLockups(item, out)
  } else if (node && typeof node === 'object') {
    const lockup = node.lockupViewModel
    if (lockup && lockup.contentType === 'LOCKUP_CONTENT_TYPE_VIDEO') {
      out.push(lockup)
    }
    for (const key of Object.keys(node)) {
      if (key === 'lockupViewModel') continue
      collectLockups(node[key], out)
    }
  }
  return out
}

function titleOf(lockup) {
  return (
    lockup.metadata?.lockupMetadataViewModel?.title?.content ?? ''
  ).trim()
}

const TYPE_BY_LABEL = [
  { label: 'SEKOLAH', type: 'Sekolah' },
  { label: 'YAYASAN', type: 'Yayasan' },
  { label: 'PONDOK PESANTREN', type: 'Pesantren' },
  { label: 'PONDOK PESANTREAN', type: 'Pesantren' },
  { label: 'PESANTREN', type: 'Pesantren' },
  { label: 'INSTANSI', type: 'Instansi' },
  { label: 'PERUSAHAAN', type: 'Perusahaan' },
  { label: 'LEMBAGA', type: 'Lembaga' }
]

const TYPE_LABEL_BY_TYPE = {
  Sekolah: 'sekolah',
  Yayasan: 'yayasan',
  Pesantren: 'pesantren',
  Instansi: 'instansi',
  Perusahaan: 'perusahaan',
  Lembaga: 'lembaga'
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function deriveType(title) {
  const upper = title.toUpperCase()
  const hit = TYPE_BY_LABEL.find(({ label }) => upper.includes(label))
  return hit ? hit.type : undefined
}

function deriveClient(title, type) {
  const parts = title.split('|')
  const client = parts[1]?.trim()
  if (!client) return undefined
  const cleaned = client
    .replace(/\s*\([^)]*\)\s*$/, '')
    .replace(/-+$/, '')
    .trim()
  return cleaned || undefined
}

const YEAR = argValue('--year') ?? '2026'

const source = argValue('--input')
const html = await loadHtml(source)
const match = html.match(/ytInitialData\s*=\s*({.+?});<\/script>/s)
if (!match) throw new Error('ytInitialData tidak ditemukan di halaman')
const data = JSON.parse(match[1])

const videos = collectLockups(data)
  .map((lockup) => ({ id: lockup.contentId, title: titleOf(lockup) }))
  .filter(({ title }) => /mars/i.test(title) && !/penjelasan/i.test(title))

if (videos.length === 0) throw new Error('tidak ada video Mars yang ditemukan')

const items = videos.map(({ id, title }) => {
  const type = deriveType(title)
  const client = deriveClient(title, type)
  if (!type || !client) {
    throw new Error(`tidak dapat memetakan judul: "${title}"`)
  }
  return {
    id: slugify(client),
    youtubeId: id,
    title: `Mars ${client}`,
    category: 'Mars',
    type,
    client,
    year: YEAR,
    description: `Mars ${client} — lagu Mars ${TYPE_LABEL_BY_TYPE[type]} untuk ${client} oleh ALF Production.`
  }
})

const types = [
  'Sekolah',
  'Yayasan',
  'Pesantren',
  'Instansi',
  'Perusahaan',
  'Lembaga'
]

const file = `// GENERATED by scripts/extract-youtube.mjs — do not edit manually
export type PortfolioCategory = 'Mars' | 'Hymne'

export type PortfolioType =
  | 'Sekolah'
  | 'Yayasan'
  | 'Pesantren'
  | 'Instansi'
  | 'Perusahaan'
  | 'Lembaga'

export interface PortfolioItem {
  id: string
  youtubeId: string
  title: string
  category: PortfolioCategory
  type: PortfolioType
  client: string
  year: string
  description: string
}

export const portfolioItems: PortfolioItem[] = [
${items
  .map(
    (item) => `  {
    id: '${item.id}',
    youtubeId: '${item.youtubeId}',
    title: '${item.title}',
    category: '${item.category}',
    type: '${item.type}',
    client: '${item.client}',
    year: '${item.year}',
    description: '${item.description}'
  },`
  )
  .join('\n')}
]

export const portfolioTypeLabels: PortfolioType[] = [
  '${types.join(`',\n  '`)}'
]

export const portfolioFilters: string[] = ['Semua', ...portfolioTypeLabels]
`

await writeFile(path.join('config', 'portfolio.ts'), file)
console.log(`config/portfolio.ts ditulis (${items.length} video Mars)`)
for (const item of items) {
  console.log(`  - ${item.youtubeId} | ${item.title} (${item.type})`)
}
